# ~/.bash_aliases

alias startw="~/.local/bin/startw.sh"

alias ls="ls --color=auto"
alias ll="ls -lav --ignore=.."
# alias l='ls -lav --ignore=.?*'   # show long listing but no hidden dotfiles except "."

alias n="nvim"
alias N="sudo nvim"
alias NF="cd ~/git/nvim-config"
alias g="cd ~/git" 
alias grubc="sudo grub-mkconfig -o /boot/grub/grub.cfg"
alias grubi="sudo grub-install"

alias fu="flatpak update"

alias mr="mullvad reconnect"

alias DF="cd ~/git/dotfiles"
alias PF="cd ~/personal"
alias LF="cd ~/personal/learn"
alias TF="cd ~/personal/tools"
alias AOC="cd ~/personal/learn/advent-of-code/aoc-2024"
