# ~/.bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

_set_my_PS1() {
    PS1="[\u@\h \W]\$ "
    if [ "$(whoami)" = "liveuser" ] ; then
        local iso_version="$(grep ^VERSION= /usr/lib/endeavouros-release 2>/dev/null | cut -d '=' -f 2)"
        if [ -n "$iso_version" ] ; then
            local prefix="eos-"
            local iso_info="$prefix$iso_version"
            PS1="[\u@$iso_info \W]\$ "
        fi
    fi
}
_set_my_PS1
unset -f _set_my_PS1

[[ "$(whoami)" = "root" ]] && return

[[ -z "$FUNCNEST" ]] && export FUNCNEST=100          # limits recursive functions, see 'man bash'


# bash config
HISTCONTROL=ignoreboth
HISTIGNORE="clear:history:exit:date:* --help"
shopt -s histappend
HISTSIZE=10000
HISTFILESIZE=5000

bind 'set completion-ignore-case on'

# Use the up and down arrow keys for finding a command in history
# (you can write some initial letters of the command first).
bind '"\e[A":history-search-backward'
bind '"\e[B":history-search-forward'


LESSHISTFILE=-

# PS1
PS1='(\[\e[38;5;45;2m\]\u\[\e[0m\]@\[\e[38;5;197m\]\h\[\e[0m\]):[\[\e[3m\]\w\[\e[0m\]] \n\\$ '

##############################
# arch news
_CheckArchNews() {
    local conf=/etc/eos-update-notifier.conf

    if [ -z "$CheckArchNewsForYou" ] && [ -r $conf ] ; then
        source $conf
    fi

    if [ "$CheckArchNewsForYou" = "yes" ] ; then
        local news="$(yay -Pw)"
        if [ -n "$news" ] ; then
            echo "Arch news:" >&2
            echo "$news" >&2
            echo "" >&2
            # read -p "Press ENTER to continue (or Ctrl-C to stop): "
        else
            echo "No Arch news." >&2
        fi
    fi
}

# pacdiff
_Pacdiff() {
    local differ pacdiff=/usr/bin/pacdiff

    if [ -n "$(echo q | DIFFPROG=diff $pacdiff)" ] ; then
        for differ in kdiff3 meld diffuse ; do
            if [ -x /usr/bin/$differ ] ; then
                DIFFPROG=$differ su-c_wrapper $pacdiff
                break
            fi
        done
    fi
}

##############################
# alias
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# ssh agent
# eval "$(ssh-agent -s)"
# if ! pgrep -u "$USER" ssh-agent > /dev/null; then
#    ssh-agent -t 1h > "$XDG_RUNTIME_DIR/ssh-agent.env"
# fi
# if [[ ! -f "$SSH_AUTH_SOCK" ]]; then
#    source "$XDG_RUNTIME_DIR/ssh-agent.env" >/dev/null
# fi
export SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/ssh-agent.socket

# fzf
eval "$(fzf --bash)"
# zoxide
eval "$(zoxide init bash)"

# alias pacdiff=_Pacdiff
