#
# ~/.bash_aliases
#
#
#
# Write in ~/.bashrc:
#
# Alias definitions.
# if [ -f ~/.bash_aliases ]; then
#     . ~/.bash_aliases
# fi 
#


alias n="nvim"
alias N="sudo nvim"
alias g="cd ~/git" 
alias grubc="sudo grub-mkconfig -o /boot/grub/grub.cfg"
alias grubi="sudo grub-install"

alias fu="flatpak update"

alias mr="mullvad reconnect"

alias commands="nvim ~/Documents/docs/commands"
alias dotfiles="/sbin/git -C ~/git/dotfiles"
alias DF="cd ~/git/dotfiles"

alias todo="nvim ~/Documents/docs/todo"
