#
# ~/.bash_aliases
#
#
#
# Write in ~/.bashrc:
#
# Alias definitions.
# if [ -f ~/.bash_aliases ]; then
#     . ~/.bash_aliases
# fi 
#

alias startw="~/.local/bin/startw.sh"

alias n="nvim"
alias N="sudo nvim"
alias NF="cd ~/git/nvim-config"
alias g="cd ~/git" 
alias grubc="sudo grub-mkconfig -o /boot/grub/grub.cfg"
alias grubi="sudo grub-install"

alias fu="flatpak update"

alias mr="mullvad reconnect"

alias DF="cd ~/git/dotfiles"
alias PF="cd ~/personal"
alias LF="cd ~/personal/learn"
alias TF="cd ~/personal/tools"
