#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

#################################################
# Environement Variables
QT_QPA_PLATFORM=xcb; export QT_QPA_PLATFORM;
QT_AUTO_SCREEN_SCALE_FACTOR=1; export QT_AUTO_SCREEN_SCALE_FACTOR;
QT_PLUGIN_PATH="/usr/lib/qt/plugins"; export QT_PLUGIN_PATH;
QT_QPA_PLATFORMTHEME=qt5ct; export QT_QPA_PLATFORMTHEME;

#################################################
### default:
#twm &
#xclock -geometry 50x50-1+1 &
#xterm -geometry 80x50+494+51 &
#xterm -geometry 80x20+494-0 &
#exec xterm -geometry 80x66+0+0 -name login
##################################################

#xrandr --output eDP-1 --mode 1920x1080
xrandr --output eDP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP-1 --off --output HDMI-1 --off --output DP-2 --off --output HDMI-2 --off --output DP-3 --off --output HDMI-3 --off
#~/.screenlayout/1080p.sh
sleep 1
#picom -f &
picom -CGb &
nm-applet &
flameshot &
dunst &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/lib/at-spi-bus-launcher --launch-immediately &
/usr/bin/snapshot-detect &
firewall-applet &
system-config-printer-applet &
mullvad-vpn &
xfce4-power-manager &
#nitrogen --restore &
betterlockscreen -w dim
xidlehook --not-when-audio --not-when-fullscreen --timer 360 "betterlockscreen -l dim" "" &

eval "$(ssh-agent -s)"

eval "$(zoxide init bash)"


#xrdb -load ~/.Xressources &
#xmodmap ~/.xmodmap &
# start i3
exec i3

