# https://dev.to/iggredible/useful-tmux-configuration-examples-k3g

# prefix
unbind C-Space
set-option -g prefix C-Space
#set-option -g prefix2 C-j
bind C-Space send-prefix

# config reload
bind-key r source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf reloaded."

# mouse
set -g mouse on

# history
set-option -g history-limit 10000

# jump to a marked pane
#bind \´ switch-client -t'{marked}'

# numbering windows und panes
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# split
# | and \\
bind-key "h" split-window -h -c "#{pane_current_path}"
bind-key "H" split-window -fh -c "#{pane_current_path}"
# - and _
bind-key "v" split-window -v -c "#{pane_current_path}"
bind-key "V" split-window -fv -c "#{pane_current_path}"

# swapping windows
# bind -r "<" swap-window -d -t -1
# bind -r ">" swap-window -d -t +1

# keeping urrent path
bind c new-window -c "#{pane_current_path}"

# toogling windows and session
bind Space last-window
# bind-key C-Space switch-client -1

#breaking and joining panes
