# autostart
#exec-once = hash dbus-update-activation-environment 2>/dev/null && \
#            dbus-update-activation-environment --systemd --all   # Wayland magic (screen sharing etc.)
# exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP QT_QPA_PLATFORMTHEME # More wayland magic (screen sharing etc.)
# exec-once = ~/.local/bin/xdg-portal.sh
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
exec-once = /usr/lib/at-spi-bus-launcher --launch-immediately
exec-once = systemctl --user restart pipewire    # Restart pipewire to avoid bugs

exec-once = hyprpaper
# exec-once = eww open bar
exec-once = mako & waybar 
# systemctl --user import-environment # exec-once = swww init && sleep 1 && swww img ~/.config/hypr/black-white-tree-grave.jpg
# exec-once = waybar

# Foot terminal daemon 
# exec-once = foot --server 

exec-once = hyprctl dispatch exec 'sleep 2s && firewall-applet'
exec-once = hyprctl dispatch exec 'sleep 2s && system-config-printer-applet'
exec-once = hyprctl dispatch exec 'sleep 2s && nm-applet --indicator'
# exec-once = xfce4-power-manager

exec-once = hyprctl dispatch exec 'sleep 2s && mullvad-vpn'

# Turn monitors off if locked (swaylock running) and idle for 10 seconds
# This will lock your screen after 300 seconds of inactivity, then turn off
# your displays after another 30 seconds, and turn your screens back on when
# resumed. It will also lock your screen before your computer goes to sleep.
# exec-once = swayidle -w # \
#            timeout 300 'swaylock -f -c 000000' \
#            timeout 330 'hyprctl dispatch dpms off' \
#            resume 'hyprctl dispatch dpms on' \
#            before-sleep 'swaylock -f -c 000000'

# hyprland plugin
exec-once = hyprpm reload -n

# apps
exec-once = [workspace 1 silent] flatpak run org.mozilla.firefox
exec-once = [workspace 2 silent] footclient

# scratchpads
exec-once = [workspace special:keepass silent] keepassxc %f
exec-once = [workspace special:element silent] element-desktop
exec-once = [workspace special:mail silent] thunderbird
