# my config

# Monitors
monitor=eDP-1,1920x1080,0x0,1
# 1920x1080@59.96 Hz
# monitor=eDP-1, modeline 172.68  1920 2040 2248 2576  1080 1081 1084 1118 -hsync +vsync, 0x0, 1
# 1920x1080@60 Hz
# monitor=eDP-1, modeline 173.00 1920 2048 2248 2576 1080 1083 1088 1120 -hsync +vsync, 0x0, 1
# fallback rule
# monitor=,preferred,auto,auto

# Environment Variables
source=/home/atchman/.config/hypr/envs.conf

# window rules
source=/home/atchman/.config/hypr/windowrules.conf

# execute your favorite apps at launch
source=/home/atchman/.config/hypr/execs.conf

xwayland {

# force_zero_scaling = true
}


input {
    kb_layout = de    # de,us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =
    # sensitivity = 1.0     # -1.0 - 1.0, 0 means no modification.
    follow_mouse = 1

    touchpad {
        natural_scroll = false
    }
}


gestures {
    workspace_swipe = false
}


# Device Config
device{
    name = logitech-wireless-mouse
    # sensitivity = 0.0
}


general {
    gaps_in = 3
    gaps_out = 10
    border_size = 2
    col.active_border = rgb(33ccff) rgba(00ff99ee) 30deg
    col.inactive_border = rgba(595959aa)
    cursor_inactive_timeout = 4
    layout = dwindle
}


decoration {
    rounding = 3
    # battery drain
    drop_shadow = false
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(00000080)
    shadow_offset = 4 4

    blur {
        # battery drain
        enabled = false
        size = 3
        passes = 1
        new_optimizations = true
    }
}


animations {
    enabled = true
    first_launch_animation = false
    # animation curves
    # https://www.cssportal.com/css-cubic-bezier-generator/
    bezier = cubic-bezier, 0.05, 0.9, 0.1, 1.05
    # animation configs
    animation = windows, 1, 7, cubic-bezier, slide
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = fade, 1, 0.0000001, default
    animation = workspaces, 1, 6, default, slide
}


dwindle {
    pseudotile = true    # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true    # you probably want this
}


master {
    new_is_master = true
    new_on_top = false
    orientation = left
}


misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    disable_autoreload = true
}


debug {
    # suppress_errors = true
}


# plugin
source=/home/atchman/.config/hypr/plugin.conf

# key binds
source=/home/atchman/.config/hypr/keybinds.conf


