# plugin configuration
# hyprpm add https://github.com/hyprwm/hyprland-plugins

plugin {
    csgo-vulkan-fix {
        res_w = 1280
        res_h = 720

        # NOT a regex! This is a string and has to exactly match initial_class
        class = cs2
    }
}
