# plugin configuration
# hyprpm add https://github.com/hyprwm/hyprland-plugins

plugin {
    csgo-vulkan-fix {
        res_w = 1368
        res_h = 768

        class = steam_app_548430
        # NOT a regex! This is a string and has to exactly match initial_class
        # class = cs2
    }
    
    csgo-vulkan-fix {
        res_w = 1600
        res_h = 900
        class = ffxiv_dx11.exe
    }
}
