# window rules
# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$


windowrulev2 = group set, class:(org.mozilla.firefox), title:(.*)(Mozilla Firefox)$
# windowrulev2 = workspace 2 silent, class:^(foot)
windowrulev2 = workspace 3 silent, class:^(gnucash)$
windowrulev2 = workspace 3 silent, class:^(Portfolio Performance)$
windowrulev2 = workspace 5 silent, class:^(XIVLauncher.Core)$
windowrulev2 = workspace 5 silent, class:^(steam)$

# scratchpads
windowrulev2 = workspace special:keepass silent, class:^(KeePassXC)$
# windowrulev2 = workspace special:discord silent, class:^(armcord)$
windowrulev2 = workspace special:discord silent, class:^(vesktop)$
windowrulev2 = workspace special:element silent, class:^(Element)$
windowrulev2 = workspace special:email silent, class:^(thunderbird)$
windowrulev2 = workspace special:locasend silent, class:^(localsend)$
windowrulev2 = workspace special:sound silent, class:^(org.pipewire.Helvum)$

# flameshot
windowrulev2=move 0 0,class:(flameshot),title:(flameshot)
windowrulev2=pin,class:(flameshot),title:(flameshot)
windowrulev2=fullscreenstate,class:(flameshot),title:(flameshot)
windowrulev2=float,class:(flameshot),title:(flameshot)

# file picker
windowrule = center, xdg-desktop-portal-gtk
windowrule = float, xdg-desktop-portal-gtk
windowrule = size 900 600, xdg-desktop-portal-gtk
windowrulev2 = float, class:chromium, title:(Open|Save) File
windowrulev2 = center, class:chromium, title:(Open|Save) File
windowrulev2 = size 900 550, class:chromium, title:(Open|Save) File

# thunderbird
windowrulev2 = center, class:thunderbird, title:^(Write)(.*)
windowrulev2 = float, class:thunderbird, title:^(Write)(.*)
windowrulev2 = size 70% 80%, class:thunderbird, title:^(Write)(.*)

# steam
windowrulev2 = move 10% 10%, class:steam, title:^(Friends)(.*)
windowrulev2 = float, class:steam, title:^(Friends)(.*)
windowrulev2 = size 30% 80%, class:steam, title:^(Friends)(.*)
windowrulev2 = center, class:steam, title:^(.*)Settings)
windowrulev2 = float, class:steam, title:^(.*)(Settings)
windowrulev2 = size 70% 80%, class:steam, title:^(.*)(Settings)

# portfolio
# windowrulev2 = center, class: Portfolio Performance, title: ()
# windowrulev2 = float, class: Portfolio Performance, title: () 
windowrulev2 = center, class:Xdg-desktop-portal-gtk, title:^(PDF-Import-Assistent)
windowrulev2 = float, class:Xdg-desktop-portal-gtk, title:^(PDF-Import-Assistent)
windowrulev2 = size 70% 80%, class:Xdg-desktop-portal-gtk, title:^(PDF-Import-Assistent)

# layers
# layerrule = 
