# workspaces

# scratchpad
workspace = special:keepass, on-created-empty:keepassxc %f
workspace = special:element, on-created-empty:element-desktop
workspace = special:mail, on-created-empty:thunderbird

workspace = special:obsidian, on-created-empty:obsidian

workspace = special:discord, on-created-empty:flatpak run dev.vencord.Vesktop
workspace = special:thunar, on-created-empty:thunar
workspace = special:localsend, on-created-empty:flatpak run org.localsend.localsend_app
workspace = special:sound, on-created-empty:helvum
