# https://starship.rs
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[character]
success_symbol = '[;](bold green)'
error_symbol = '[!](red)'

[aws]
symbol = "☁️ "
disabled = false

[[battery.display]]
threshold = 20
style = 'bold red'

[[battery.display]] 
threshold = 30 
style = 'bold yellow'

[c]
symbol = " "

[custom.quadlet]
description = 'Podman Quadlet'
command = "podman --version | awk '{ print $3 }'"
shell = ['fish', '-N']
detect_extensions = ['container', 'network', 'volume', 'pod']
symbol = "🦭 "
style = 'purple'
format = 'via [$symbol($output )]($style)'

[directory]
read_only = " 󰌾"

[docker_context]
# symbol = " "

[elixir]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "

[git_commit]
tag_symbol = '  '

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[hostname]
ssh_symbol = "🌐 "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "
disabled = true

[perl]
disabled = true

[python]
symbol = " "

[rust]
symbol = "󱘗 "

[zig]
symbol = " "
