# configuration for xdg-user-dirs-update
# when set to False, 
# xdg-user-dirs-update will not change the XDG user dirs configuration

enabled=True

# This sets the filename encoding to use. 
# encoding can be an explicit encoding name, such as UTF-8, or "locale", 
# which means the encoding of the users locale will be used.

filename_encoding=UTF-8
