# executing 
### exec-once=command will execute only on launch
### exec=command will execute on each reload


### start
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP    # More wayland magic (screen sharing etc.)
exec-once = hash dbus-update-activation-environment 2>/dev/null && \
            dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP    # Wayland magic (screen sharing etc.)
exec-once = /home/atchman/.config/hypr/scripts/xdg-portal.sh
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
exec-once = /usr/lib/at-spi-bus-launcher --launch-immediately
exec-once = systemctl --user restart pipewire    # Restart pipewire to avoid bugs


#exec-once = swww init && sleep 1 && swww img /home/atchman/.config/hypr/black-white-tree-grave.jpg
exec-once = hyprpaper
#exec-once = eww open bar
exec-once = mako &
exec-once = waybar

# Foot terminal daemon 
exec-once = foot --server 

exec-once = wl-paste --watch cliphist store


exec-once = hyprctl dispatch exec "sleep 2s && firewall-applet"
exec-once = hyprctl dispatch exec "sleep 2s && system-config-printer-applet"
exec-once = hyprctl dispatch exec "sleep 2s && nm-applet --indicator"
#exec-once = xfce4-power-manager

exec-once = hyprctl dispatch exec "sleep 2s && mullvad-vpn"
#exec-once = flameshot


# Turn monitors off if locked (swaylock running) and idle for 10 seconds
# This will lock your screen after 300 seconds of inactivity, then turn off
# your displays after another 30 seconds, and turn your screens back on when
# resumed. It will also lock your screen before your computer goes to sleep.
exec-once = swayidle -w \
                timeout 300 'swaylock -f' \
                timeout 330 'hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on' \
                before-sleep 'swaylock -f'


# autostart
exec-once=[workspace 2 silent] foot
#exec-once = [workspace 1 silent] LibreWolf
#exec-once = [workspace 1 silent] brave
#exec-once = [workspace 6 silent] keepassxc
#exec-once = [workspace 9 silent] thunderbird
#exec-once = [workspace 8 silent] element-desktop

