# executing 
### exec-once=command will execute only on launch
### exec=command will execute on each reload


### start
exec-once = ~/.config/hypr/scripts/xdg-portal.sh
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP    # Wayland magic (screen sharing etc.)
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP    # More wayland magic (screen sharing etc.)
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = systemctl --user restart pipewire    # Restart pipewire to avoid bugs


exec-once = hyprpaper
#exec-once = eww open bar
exec-once = waybar
exec sleep 2
exec-once = mako

exec-once = wl-paste --watch cliphist store
#exec-once = /usr/lib/at-spi-bus-launcher --launch-immediately



exec-once = "sleep 8; firewall-applet"
exec-once = system-config-printer-applet
exec-once = nm-applet --indicator
#exec-once = xfce4-power-manager

exec-once = mullvad-vpn
#exec-once = flameshot


# Turn monitors off if locked (swaylock running) and idle for 10 seconds
#exec-once = swayidle -w timeout 10 'if pgrep -x swaylock; then hyprctl dispatch dpms off; fi' resume 'hyprctl dispatch dpms on' 
# Lock screen after idle for 300s and turn monitors off after 330
exec-once = swayidle -w timeout 300 'swaylock -f -C $dir/swaylock/config' timeout 330 'hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on'


# autostart
#exec-once = brave
#exec-once = thunderbird
#exec-once = element-desktop
#exec-once = keepassxc

