# hardened ssh config

Protocol 2

ForwardX11 no
ForwardX11Trusted no

Tunnel no
ForwardAgent no

GSSAPIAuthentication no
HostbasedAuthentication no

# SendEnv

StrictHostKeyChecking ask

# CVE-2016-0777 CVE-2016-0778
UseRoaming no

Ciphers -arcfour*,-*cbc

RequiredRSASize 4096


Host *
    Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com #,aes256-ctr,aes192-ctr,aes128-ctr
    MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com #,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com
    